### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by Leiocera** [qouteall/ImmersivePortalsModForForge#126]
If I start Minecraft with this mod, Minecraft crashes.

**PLEASE HELP!!!**

Here's the video link:
https://www.youtube.com/watch?v=qHPh1Xg5ba8

The log file is here:

`[13:44:59] [main/INFO]: ModLauncher running: args [--username, LeioceraYT, --version, forge-31.2.9, --gameDir, C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY, --assetsDir, C:\Users\LeioceraYT\Twitch\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, f1aeb725a16943c4b8659a17ab5f4b55, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.9, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[13:44:59] [main/INFO]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_51 by Oracle Corporation
[13:45:00] [main/INFO]: OptiFineTransformationService.onLoad
[13:45:00] [main/INFO]: OptiFine ZIP file: C:\Users\Manuel\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\OptiFine_1.15.2_HD_U_G1_pre18_MOD.jar
[13:45:00] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[13:45:00] [main/INFO]: OptiFineTransformationService.initialize
[13:45:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/LeioceraYT/Twitch/Minecraft/Instances/DOORSOFINFINITY/mods/MixinBootstrap-1.0.3.jar Service=ModLauncher Env=CLIENT
[13:45:01] [main/WARN]: File C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\doorsofinfinity-1.0.1.jar has been ignored - it is invalid
[13:45:01] [main/WARN]: Mod file Mod File: C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\Skin Swapper 1.15.2.jar is missing mods.toml file
[13:45:01] [main/WARN]: File C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\Skin Swapper 1.15.2.jar has been ignored - it is invalid
[13:45:02] [main/INFO]: OptiFineTransformationService.transformers
[13:45:02] [main/INFO]: Targets: 278
[13:45:02] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[13:45:02] [main/INFO]: Successfully loaded Mixin Connector [com.qouteall.hiding_in_the_bushes.MyMixinConnector]
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: net/minecraft/util/math/RayTraceResult
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.qouteall.hiding_in_the_bushes.MyMixinConnector.connect(MyMixinConnector.java:13)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.initConnectors(MixinConnectorManager.java:96)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:61)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:194)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$12(LaunchPluginHandler.java:95)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$427/2074492901.accept(Unknown Source)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1280)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:95)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: net.minecraft.util.math.RayTraceResult
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[13:45:02] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 14 more
`

**Comment by qouteall** [comment]
Try to use the latest optifine and uninstall optiforge.

**Comment by Leiocera** [comment]
It's still crashing :(

**Comment by qouteall** [comment]
what's the new crash report

**Comment by Leiocera** [comment]
[14:11:24] [main/INFO]: ModLauncher running: args [--username, LeioceraYT, --version, forge-31.2.9, --gameDir, C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY, --assetsDir, C:\Users\LeiocerYT\Twitch\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, f1aeb725a16943c4b8659a17ab5f4b55, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.9, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[14:11:24] [main/INFO]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_51 by Oracle Corporation
[14:11:25] [main/INFO]: OptiFineTransformationService.onLoad
[14:11:25] [main/INFO]: OptiFine ZIP file: C:\Users\LeioceraYT\Twitch\Minecraft\Instances\DOORSOFINFINITY\mods\OptiFine_1.15.2_HD_U_G1_pre26_MOD.jar
[14:11:25] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[14:11:25] [main/INFO]: OptiFineTransformationService.initialize
[14:11:25] [main/FATAL]: Failed to find Minecraft resource version 1.15.2-20200515.085601 at C:\Users\Manuel\Twitch\Minecraft\Install\libraries\net\minecraftforge\forge\1.15.2-31.2.9\forge-1.15.2-31.2.9-client.jar
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: Missing minecraft resource!
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.lambda$validatePaths$4(FMLCommonLaunchHandler.java:124)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler$$Lambda$155/1194893830.accept(Unknown Source)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:121)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:199)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:92)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$86/522553046.accept(Unknown Source)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap$Values.forEach(HashMap.java:972)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[14:11:25] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by ghost** [comment]
optiforge isn't even mandatory, as optifine works as a forge mod just fine

**Comment by Leiocera** [comment]
It's still crashing!

**Comment by Leiocera** [comment]
[14:32:11] [main/INFO]: ModLauncher running: args [--username, LeioceraYT, --version, forge-31.2.20, --gameDir, C:\Users\LeioceraYT\Twitch\Minecraft\Instances\1.15.2 FORGE SERVER, --assetsDir, C:\Users\Manuel\Twitch\LeioceraYT\Install\assets, --assetIndex, 1.15, --uuid, f1aeb725a16943c4b8659a17ab5f4b55, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.2.20, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200515.085601]
[14:32:11] [main/INFO]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_51 by Oracle Corporation
[14:32:11] [main/INFO]: OptiFineTransformationService.onLoad
[14:32:11] [main/INFO]: OptiFine ZIP file: C:\Users\LeioceraYT\Twitch\Minecraft\Instances\1.15.2 FORGE SERVER\mods\preview_OptiFine_1.15.2_HD_U_G1_pre26.jar
[14:32:11] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[14:32:11] [main/INFO]: OptiFineTransformationService.initialize
[14:32:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/LeioceraYT/Twitch/Minecraft/Instances/1.15.2%20FORGE%20SERVER/mods/MixinBootstrap-1.0.3.jar Service=ModLauncher Env=CLIENT
[14:32:13] [main/INFO]: OptiFineTransformationService.transformers
[14:32:13] [main/INFO]: Targets: 285
[14:32:13] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[14:32:13] [main/INFO]: Successfully loaded Mixin Connector [com.qouteall.hiding_in_the_bushes.MyMixinConnector]
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: net/minecraft/util/math/RayTraceResult
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at com.qouteall.hiding_in_the_bushes.MyMixinConnector.connect(MyMixinConnector.java:13)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.initConnectors(MixinConnectorManager.java:96)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:61)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:197)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:190)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.initializeLaunch(MixinLaunchPlugin.java:194)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$12(LaunchPluginHandler.java:95)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$419/1425405511.accept(Unknown Source)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1280)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:95)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: net.minecraft.util.math.RayTraceResult
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[14:32:13] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 14 more

**Comment by ghost** [comment]
java.lang.NoClassDefFoundError: net/minecraft/util/math/RayTraceResult have you tried reinstalling minecraft?

**Comment by Leiocera** [comment]
No, it's with the Twitch-Launcher.

I tried it several times.

**Comment by ghost** [comment]
the twitch launcher is the issue

**Comment by LeioceraYT** [comment]
How can I fix the issue? Or how can I install Forge for 2 versions? I already have forge for the 1.12.2, but how can I add another? And another?

**Comment by Leiocera** [comment]
How can I fix the issue; how can I install forge for 2 versions? I hope, you understand what I mean, I have Forge for 1.12.2, but I ALSO want Forge for the 1.15.2. But how can I do this? I hope for an answer.

**Comment by Kilomegaminx** [comment]
I have had the same issue and discovered that OptiFine itself is the issue. You can get rid of OptiFine and it should work, but then the issue still stands: NO OPTIFINE!!!

Update: It now crashes when loading up a world. Sorry, I realize now that this should be a separate issue.

**Comment by Leiocera** [comment]
How can I install forge for 2 versions? I hope, you understand what I mean, I have Forge for 1.12.2, but I ALSO want Forge for the 1.15.2. But how can I do this? I hope for an answer.

**Comment by ghost** [comment]
Use MultiMC (google MultiMC and you will find it)

**Comment by Leiocera** [comment]
Thx but unfortunately it's not working for 1.14+

**Comment by DArkHekRoMaNT** [comment]
> Thx but unfortunately it's not working for 1.14+

At the moment, MultiMC is already working with 1.15.2 and Forge. C 1.14 I did not check, but I think everything should be fine too.
